### ISSUE TITLE
Placeholder for modifier class not displaying in sample code

### ISSUE THREAD

**Issue by ethikz** [kss-node/kss-node#167]
I am using a custom template based off the default template and have added my styles.  My css works but the issue I see is then the actual source displaying.

The actual code is
````
<a href="#" class="button button--primary">Link Button</a>
````

When viewing the kss markup it doesn't display the modifier
````
<a href="#" class="button ">Link Button</a>
````

My scss markup is
````
// Buttons
//
// A majority of buttons in the site are built from the same base class.
//
// Markup:
// <a href="#" class="button {{modifier_class}}">Link Button</a>
// <button class="button {{modifier_class}}">Button Element</button>
// <input type="button" class="button {{modifier_class}}" value="input[type='button']"/>
//
// .button--primary   - Use this class to indicate that the button is the primary
//              feature of this form.
// :hover     - Highlight the button when hovered.
//
// Styleguide components.buttons 
````

**Comment by sgregson** [comment]
Is your markup field being output using triple brackets? I was hitting this issue too and noticed my template was using `{{markup}}` instead of `{{{markup}}}`

See handlebars docs on escaping HTML at http://handlebarsjs.com/#html-escaping

**Comment by ethikz** [comment]
Thanks for that but unfortunately that isn't the case, it is using ````{{{markup}}}````

**Comment by bbialas** [comment]
Hi,

probably this is a problem with template file. I have the same problem, but I modified my template file like this and now everything is fine :)

```
<div class="kss-markup">
    <pre>
        <code data-language="html">{{markup}}</code>
        {{#eachModifier}}<code data-language="html">{{markup}}</code><br>{{/eachModifier}}
    </pre>
</div>
```

**Comment by sgregson** [comment]
@ethiks, I see what you're talking about - this is also happening on the default template. The demo styleguide shows it on the buttons example at http://kss-node.github.io/kss-node/section-components.html#kssref-components.buttons

**Comment by ethikz** [comment]
Oh great I didn't realize it.  Is there a solution or workaround?

**Comment by joaogarin** [comment]
Hello,

is there any solution to this? Having the same issue with the default template. 

My comment is like this : 

// Button
//
// Your standard button suitable for clicking.
//
// Markup:
// <a href="#" class="btn {$modifiers}">Link Button</a>
// <button class="btn {$modifiers}">Button Element</button>
//
// .btn-primary   - Primary button. The style main button.
// .btn-success   - Success button.
//
// Styleguide components.buttons

And it renders class="btn {{modifier_class}}" instead of class="btn btn-primary"

**Comment by chloeleichen** [comment]
Having the same issue, any one can help?

**Comment by bm2u** [comment]
Having the same problem without any workaround. Although it does not break the styleguide, it hurts extremely.

**Comment by sgregson** [comment]
You should be able to use this as a workaround - it's working in my templates at least.

1) add this to your helpers
```js
module.exports.register = function(handlebars) {
  /**
   * Outputs the current section's or modifier's markup with the {{modifier_class}} preserved
   */
  handlebars.registerHelper('markup-sample', function() {
    if (!this.markup) {
      return '';
    }
    return this.markup;
  });
};
```

2) Wherever you're displaying the example use `{{markup-sample}}` in the index.html of your template instead of `{{markup}}`  (leave the modifiers lists alone `{{markup}}`)

@JohnAlbin any info on the source/resolution of this bug? The workaround makes quick work of the issue, but I'd think this should probably be handled somehow in the core markup helper. Maybe as an optional param? `{{markup showclass="true"}}` etc

**Comment by sgregson** [comment]
If you're using partials for your markup you can do something like this, which is pretty gross. It's a little more maintainable than littering your codebase with `class="{{modifier_class}} \{{modifier_class}}"`, but still pretty hacky.

1) Again, in your helpers - this time it checks for a .hbs file and compiles it
```js
if (!String.prototype.endsWith) {
  Object.defineProperty(String.prototype, 'endsWith', {
    value: function(searchString, position) {
      var subjectString = this.toString();
      if (position === undefined || position > subjectString.length) {
        position = subjectString.length;
      }
      position -= searchString.length;
      var lastIndex = subjectString.indexOf(searchString, position);
      return lastIndex !== -1 && lastIndex === position;
    }
  });
}

module.exports.register = function(handlebars) {
  /**
   * Outputs the current section's or modifier's markup with the {{modifier_class}} preserved
   */
  handlebars.registerHelper('markup-sample', function(options) {
    if (!this.markup) {
      return '';
    }
    var template, output;

    if (this.markup.endsWith('.hbs')) {
      template = handlebars.compile('{{> ' + this.markup.replace('.hbs', '') + ' }}');
      output = template();
    } else {
      output = this.markup;
    }
    return output;
  });
};
```

2) handlebars markup partials need to have an escaped modifier_class as well as the usual one, this way one will compile for the modifiers lists and the other will appear in your markup list.

```handlebars
<div class="{{modifier_class}} \{{modifier_class}} small">lorem ipsum</div>
<div class="{{modifier_class}} \{{modifier_class}}">lorem ipsum</div>
<div class="{{modifier_class}} \{{modifier_class}} medium">lorem ipsum</div>
<div class="{{modifier_class}} \{{modifier_class}} large">lorem ipsum</div>
<div class="{{modifier_class}} \{{modifier_class}} mega">lorem ipsum</div>
```

3) in your template, use `{{markup-sample}}` for your markup sample and `{{markup}}` for your modifiers lists

**Comment by JohnAlbin** [comment]
@ethikz Can you confirm that the issue you are having is that the text "{{modifier_class}}" doesn't appear in the style guide's web page? e.g. http://kss-node.github.io/kss-node/section-forms.html#kssref-forms.text.single-line shows `<input type="text" class="" value="Text input"/>` instead of what you expected, `<input type="text" class="{{modifier_class}}" value="Text input"/>`?

In the old version of kss-node, some people thought displaying  `<input type="text" class="{$modifiers}" value="Text input"/>` in the sample source code confusing. After I integrated Handlebars, the `{{modifier_class}}` variable is completely empty for the "default styling" version, so that confusing, but semi-helpful text went away.

Since there seems to be a bunch of people who want this "fixed", can you chime in to give suggestions about what wouldn't be confusing? Specifically non-developers don't know Handlers `{{variable}}` syntax, so can you suggest alternatives to `<input type="text" class="{{modifier_class}" value="Text input"/>`?

Also, it sounds like there are 2 issues being discussed here. @joaogarin’s issue sounds different than the originally described issue. `{$modifiers}` is the old way to insert modifier classes. kss-node 2.x uses Handlebars variables like `{{modifier_class}}`. So fixing your markup should solve your issue.

And @chloeleichen and @bm2u, you chimed in without any details, so I don't know which of the 2 issues you are having.

**Comment by bm2u** [comment]
@JohnAlbin I would like to get the value (class name) of the modifier instead of {$modifier} or any other placeholder or empty string.

**Comment by sgregson** [comment]
@JohnAlbin I'd want the markup sample (kss-markup-original) to indicate where the modifier should be inserted. Since modifiers are agnostic about their content, capable of being id/class/pseudo/copy, they can be used as anything and dropped in anywhere in the markup, which should be visibly documented in the styleguide.

Two patterns, to illustrate why subtle differences in the insertion point makes it useful to have some kind of placeholder in the sample markup:

#### as value for html attribute
```scss
// Icons as css content
// 
// Markup: <i class="icon {{$modifier_class}}"></>
//
// .large-smiley - creates a large smiley
// 
// Styleguide icons.modern
```

#### as html content
```scss
// Icons as htmlentity
// 
// Markup: <i class="icon">{{$modifier_class}}</>
//
// &#58933; - creates a large smiley
// 
// Styleguide icons.oldschool
```

**Comment by JohnAlbin** [comment]
@bm2u I suspect you are having a different problem from the one we are discussing. The "solution" you are requesting doesn't make sense. Having a modifier means you have multiple possible values for {{modifier_class}}, so I can't display "the actual value".

@sgregson You've reiterated the original problem very well, but you didn't actually answer the question I asked above:

> non-developers don't know Handlebars’ `{{variable}}` syntax, so can you suggest alternatives to `<input type="text" class="{{modifier_class}" value="Text input"/>`?

**Comment by sgregson** [comment]
fair point. I didn't really have issue with `{{modifier_class}}` so I hadn't considered the adjustment. "the_modifier" would get away from modifier-as-class and is still consistent with KSS.



















































































































































































































































































































































































































































































































































































































































Do you think the problem is more with the naming of "modifier_class" or the representation of handlebars syntax "{{}}" in the generated styleguide docs. 

`<input type="text" class="{the_modifier}" value="Text input"/>`

**Comment by ethikz** [comment]
@JohnAlbin I can confirm that "{{modifier_class}}" doesn't appear in the style guide's web page, like the link you showed.  With it not showing in the default element with default class that is fine.  The issue is with all the other modifiers not showing and appearing like this `<input type="text" class="" value="Text input"/>`

**Comment by matthewferry** [comment]
@JohnAlbin Yeah I think the main issue is when the html is a bit more complex, like for example using a component that may have modifiers on decendents. For the button example, I can see why some people may not want the {{modifier_class}} to show in the example. But let's look at something with a bit more meaty markup — something like the classic Nicole Sullivan media object:
```
<div class="media">
  <div class="media-img {{modifier_class}}">
    <img src="http://placeimg.com/80/80/animals" />
  </div>
  <div class="media-content">
    [some_content_here]
  </div>
</div>
``` 
In that example, I would love to have the code example show *where* the modifier needs to be added, so that when someone reads the markup, they know what to do.

**Comment by JohnAlbin** [comment]
I'm going to use `[modifier class]` as the placeholder text in default code sample.

**Comment by JohnAlbin** [comment]
There's also a new `--placeholder` option if you don't like the default `[modifier class]` text.

**Comment by bm2u** [comment]
@JohnAlbin thank you. excellent work - absolutly fabulous :+1: 

Am I right in assuming that "--placehoder" and "--title" is only available for the default-template. Otherwise I have not understood how to use these options, yet  (would appreciate an small example).

**Comment by createdotmatt** [comment]
@JohnAlbin thanks for updating this. Would you be able to clarify what I would need to get this working? I have updated to the latest version but the modifiers are still being removed from my examples. Would it be anything to do with my template?
```
<div>
	<div class="kss-modifier__example">
		{{{markup}}}
	</div>
  	
	{{#eachModifier}}
		<div class="kss-modifier__name kss-style">
	  		{{name}}
		</div>
		
		<div class="kss-modifier__description kss-style">
	  		{{{description}}}
		</div>

		<div class="kss-modifier__example">
	  		{{{markup}}}
		</div>
  	{{/eachModifier}}

</div>

<div class="kss-markup kss-style">
	<pre class="prettyprint linenums lang-html"><code data-language="html">{{markup}}</code></pre>
</div>
```
