### ISSUE TITLE
Remove dots in {{referenceURI}}

### ISSUE THREAD

**Issue by danielditgens** [kss-node/kss-node#174]
Hi,

i am using {{referenceURI}} for classes and even for id's, but if want to use them as selector these via jQuery or CSS I have to escape the dots which is frankly spoken unhandy.

Maybe you can provide an alternative:

```
class="ref{{_referenceURI}}" may result in class="ref-elements-forms-buttons"
```

**Comment by phobia** [comment]
You could probably solve this by adding a custom Handlebars helper.

If you create a directory named helpers on the kss-node root, and a file within named for example myHelpers.js, containing this:

```
module.exports.register = function(handlebars) {
  handlebars.registerHelper('dashify', function(str, options) {
    return new handlebars.SafeString(str.replace('.', '-'));
  });
};
```

and then in the template instead of ```{{referenceURI}}``` you could use ```{{dashify referenceURI}}```.

You'd have to tell kss-node about this helpers folder though, by adding `--helpers helpers/` when running it.

**Comment by danielditgens** [comment]
Now I created a helper:
```
module.exports.register = function(handlebars) {
  handlebars.registerHelper('dashify', function(str, options) {
    return new handlebars.SafeString(str.replace(/\./g, '-'));
  });
};
```
Works fine with me. Many, many thanks!

**Comment by JohnAlbin** [comment]
@phobia Thanks for helping out in the issue queue! That's a great work-around.

Whoops. Yeah, I just inspected the demo docs and found this:

```
<section id="kssref-forms.text.single-line" class="kss-section kss-section--depth-3">
```
That's not so good.
