### ISSUE TITLE
Rename public folder to "kss-assets" so KSS does not delete all files in public

### ISSUE THREAD

**Issue by akrawchyk** [kss-node/kss-node#176]
https://github.com/kss-node/kss-node/blob/e3f4a80a43ba55a1695b0a2539d062c4c338e3d4/generators/handlebars/kss_handlebars_generator.js#L53

This line force deletes all files in the public folder. If I've included any other assets in a build process to that folder before generating a styleguide, they will be destroyed by this generator.

Is this intentional?

**Comment by JohnAlbin** [comment]
From a technical stand point, that's the way Wrench works. From the [Wrench homepage](https://github.com/ryanmcgrath/wrench-js#possibly-breaking-change-in-v150):

>  if you try to copy over a directory that already exists, you'll get an Error returned or thrown stating that you need to force it.

From a "how does kss-node _need_ to work" stand point:

If you've run the style guide generation process at least once, I need to replace the existing "template asset folder" with a new copy. And since I use Wrench, I have to delete the old one to do that.

Do I need the "template asset folder" be called "public"? No. But I would need to call it something. And you won't be able to put your own stuff into that folder, no matter what it is named.

I've just added a WARNING.txt file to that folder to wave off other people making the same mistake.

Is naming the folder "public" an issue? I've never used a folder called "public" in any of my web projects. I use "css" and "js", etc.

Hmm… thinking about this, I can imagine "public" being a semi-common naming convention. And it's no good having kss-node prevent anybody's naming convention.

I'll rename the "public" folder to something else. And you can use "public" for whatever you want.

**Comment by JohnAlbin** [comment]
Oh, bugger. I just realized that changing the folder name would be a breaking API change. 3rd party templates are depending on kss-node copying their public folders to the generated style guide.

We'll have to wait until 3.0 before making this change.

**Comment by akrawchyk** [comment]
Thanks for making this update @JohnAlbin!
