### ISSUE TITLE
Support for preprocessor functions and mixins

### ISSUE THREAD

**Issue by Anahkiasen** [kss-node/kss-node#22]
It seems like mixins and functions, at least in SASS/SCSS, aren't parsed correctly.
Take the following simple block :

```scss
// @arrow-bottom($size, $color)
//
// Generates an arrow on the bottom of the block
//
// $size  - The size of the arrow
// $color - Its color
//
// Styleguide 1.2.2.
```

As `kss-node` is interpreting the arguments as modifiers, it doesn't display them without a provided markup. 
Mixins and functions shouldn't have any markup – ever – and thus the parser should skip straight to the modifiers and display them as arguments.

**Comment by JohnAlbin** [comment]
> As kss-node is interpreting the arguments as modifiers, it doesn't display them without a provided markup. 

Oh! I was trying to figure out how to get kss-node to tell the difference between a preprocessor helper docblock and a regular docblock. And I think that's the key!

If the docblock has a block that looks like modifiers, but has no markup block, then kss-node can display those as parameters instead of modifiers.

**Comment by MadLittleMods** [comment]
:+1:

**Comment by JohnAlbin** [comment]
Fixed!

**Comment by MadLittleMods** [comment]
Thanks :)  - Is there any chance this could be published to npm before the [full 2.0 checklist todo](https://github.com/kss-node/kss-node/issues/154) is done? 

I'll install from the repo for now: `npm install kss-node/kss-node`

**Comment by varemenos** [comment]
@MadLittleMods You will most probably be able to install it once  "2.0.0-alpha.5" is released

**Comment by MadLittleMods** [comment]
I just tried this and it doesn't seem to work. I am using Sass scss.

I grabbed this example from the [gh-pages demo](http://kss-node.github.io/kss-node/#preprocessor-helper-documentation), *also on the [KSS site](http://warpspire.com/kss/syntax/)*

```
// Creates a linear gradient background, from top to bottom.
//
// $start - The color hex at the top.
// $end   - The color hex at the bottom.
//
// Compatible in IE6+, Firefox 2+, Safari 4+.
@mixin gradient($start, $end){
  ...
}
```

The only way I can get it to parse is if I add a `// Styleguide 6.4` section declaration on the last line. 

In that example, kss-node uses the description as the the `header`.

If I add a a header(which is repetitive because it is right there in the mixin), then it lumps the description, parameters, and compatibility into the `description`. I see that @JohnAlbin  [added a section declaration in his commit](https://github.com/kss-node/kss-node/commit/26b337f98c9e5a6caa9b731f2c359b37c906ad7f#diff-9b58b6bcf142af2b233126411873c50cR25) and a title.

Should it work without a header?

**Comment by JohnAlbin** [comment]
FYI, I'm using this feature already on a production web site. It's included with https://github.com/kss-node/kss-node/releases/tag/v2.0.0-beta.1

I've already opened a github discussion in the kss queue about the problem with showing a preprocessor example that doesn't have a `Styleguide [ref]` declaration. https://github.com/kneath/kss/pulls How does that even make sense? If a CSS comment doesn't have a `Styleguide [ref]` how can it be a KSS doc block? How would any kss parser know where to put the documentation if the user doesn't define where in the style guide hierarchy the preprocessor docs should go. The spec is too vague here.

The latest docs I wrote for kss-node v2 include an annotated spec at https://github.com/kss-node/kss/blob/spec/SPEC.md . That spec is clearly noted in the README, but won't appear on the kss-node homepage until v2 is released and the master branch becomes the default branch (instead of 1.x.) That will happen sometime in the next week.
