### ISSUE TITLE
Syntax Error when using --clone on Windows

### ISSUE THREAD

**Issue by sfulghum** [kss-node/kss-node#307]
I've run into an issue using the clone option for creating a new template.

Here's the output:
` ./node_modules/.bin/kss-node --clone custom-builder
Creating a new style guide builder in C:\working\kss_poc_v3\custom-builder...`
`SyntaxError: Invalid regular expression: /^(?!.*\(node_modules$|\.))/: Unmatched ')'`

This happens with beta.1 and beta.5, on Node 5 and Node 6, all running on Win7. Both with local and global installations as well.

2.4's --init option works fine, so I can fallback to that for the time being. Is the plan for 3.0 to have backwards compatibility with 2.x    @##templates?

**Comment by ParamRandhawa** [comment]
I got the same error just now.

C:\gns-web-style-guide>kss-node --clone
Creating a new style guide builder in C:\gns-web-style-guide\custom-builder...
SyntaxError: Invalid regular expression: /^(?!.*\(node_modules$|\.))/: Unmatched ')'

**Comment by param-randhawa** [comment]
I reported this issues here as well, but the was closed :(

https://github.com/kss-node/kss-node/issues/302

**Comment by param-randhawa** [comment]
@sfulghum any luck resolving this issue?

**Comment by JohnAlbin** [comment]
> I reported this issues here as well, but the was closed :(... #302

@param-randhawa No, you didn't. You reported a completely different error message which was the result of you not reading the documentation I asked you to read two different times in the same issue. Please don't insinuate that I close issues of people with legitimate problems. Your issue in #302 started as a legitimate support request. I asked you to read the docs. You did not and came back with a different problem. I asked you to read the docs again. You did not and came back with a new problem. I told you the answer and then locked the issue because you weren't respecting my time.

@sfulghum Hmm… that shouldn't be happening. Let me investigate.

**Comment by JohnAlbin** [comment]
Yep. It's a bug when running kss-node on Windows. Thanks for reporting! I'll get it fixed pronto.

**Comment by JohnAlbin** [comment]
It looks like PR #280 missed one of the spots it needed to fix.

**Comment by JohnAlbin** [comment]
Fixed! I'll roll a new beta later today.

**Comment by param-randhawa** [comment]
@JohnAlbin  Thanks!
