### ISSUE TITLE
Styleguide reference default ordering by order of appearance? (not alphabetical)

### ISSUE THREAD

**Issue by tsi** [kss-node/kss-node#357]
From the docs -

> References may also be period seperated word keys. Leading words denote hierarchy.

That's awesome

> If you are using word keys or word phrases as your style guide references, kss-node will sort all sections using alphabetical order

I don't get this, it would be so much easier just to go by order of appearance, this way we'll be able to control the ordering simply by changing the order of our ```@import```s.

**Comment by tsi** [comment]
Looking at the code, it seams like the style guide is not generated from my master scss file at all.
Instead, It goes over everything in the source directory.
So not only that I can't re-order my ```@import```s - if I **remove** an ```@import``` it will still show in the style guide, even if it's not included in my CSS output.
Is that correct?

**Comment by JohnAlbin** [comment]
@tsi kss-node does not parse Sass, Less, or any preprocessor syntax. It just looks through text files for KSS-style comments. We did that intentionally because there are 800 different ways to compile Sass and Less, etc. And we would have had to replicate a particular users build method in order to know the order that files are parsed.

If you want to remove a KSS section from the guide, you just need to change the last line to one that KSS does not recognize as valid. For example:

```scss
// Section
//
// Style guide: custom.section
```
change the last line like so:
```scss
// Section
//
// No Style guide: custom.section
```
