### ISSUE TITLE
css source is not based on destination

### ISSUE THREAD

**Issue by MartinMuzatko** [kss-node/kss-node#398]
Hello!

When I generate my styleguide, I need to set the path for the CSS relative to the `destination`.
So I have to change the `css` path relative to the destination. (Which differs from the `source`).

```sh
kss --css ../build/base.css --source base/less --destination guide
```

Instead, it would be nice to have relative paths computed by the `destination` folder.

```sh
kss --css build/base.css --source base/less --destination guide
```

**Comment by JohnAlbin** [comment]
The `--css` option doesn't take a path. It takes a URL. So if you give it a string that looks like this "../build/base.css" or "build/base.css", you are giving it a URL relative to the generated HTML of your style guide.

Here's the docs from the homepage of this project:
> --css          URL of a CSS file to include in the style guide

kss does not know how the webserver is configured so it could very easily get the URL wrong given a relative _path_ (which by UNIX convention would need to be relative to the current directory when the user started the kss command). This would be a whole class of errors (and bug reports) that would be hard to debug and frustrating to users. Your bug was relatively easy to figure out. And, so, is the lessor of 2 bad outcomes.
